"""add_job_structured_fields

Revision ID: 3a42b5d4dafd
Revises: 8f208b361863
Create Date: 2026-08-04 00:27:39.904578

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a42b5d4dafd'
down_revision: Union[str, None] = '8f208b361863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferred_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('normalized_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('job_parser_version', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('job_parser_version')
        batch_op.drop_column('normalized_title')
        batch_op.drop_column('preferred_skills')
        batch_op.drop_column('required_skills')

    # ### end Alembic commands ###
