"""add_missing_columns

Revision ID: 82776d9dcbdf
Revises: 0004_users_resumes_matches
Create Date: 2026-07-25 08:32:28.909109

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82776d9dcbdf'
down_revision: Union[str, None] = '0004_users_resumes_matches'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_matches_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_interval_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiet_hours_start', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours_end', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('quiet_hours_end')
        batch_op.drop_column('quiet_hours_start')

    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.drop_column('poll_interval_minutes')

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_job_id'))
        batch_op.drop_column('notified_at')

    # ### end Alembic commands ###
