"""add_hybrid_scoring_columns

Revision ID: 8f208b361863
Revises: 0010_user_hashed_password
Create Date: 2026-08-04 00:20:10.030574

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f208b361863'
down_revision: Union[str, None] = '0010_user_hashed_password'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_breakdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('scoring_version', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_column('scoring_version')
        batch_op.drop_column('score_breakdown')

    # ### end Alembic commands ###
